"""empty message

Revision ID: 38f8941a9885
Revises: 2d6224f91388
Create Date: 2026-01-20 12:58:36.951986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f8941a9885'
down_revision = '2d6224f91388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('hasApplied')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hasApplied', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
